name: Audit

on:
  push:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-20.04
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup golang
        uses: actions/setup-go@v2   
      - name: Build code
        run: make cicd_build
      - name: SCP to EC2.
        env: 
          PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
          USER_NAME: ${{secrets.USER_NAME}}
          HOST_NAME: ${{secrets.HOST_NAME}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          printf " here is the private key ${PRIVATE_KEY}/n"
          scp -o StrictHostKeyChecking=no -i private_key -r ./app ${USER_NAME}@${HOSTNAME}:/home/ubuntu/lcm
          