name: Audit

on:
  push:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-20.04
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup golang
        uses: actions/setup-go@v2   
      - name: Build code
        run: go build -v ./...
      - name: Run tests
        run: go test